name: Build and Deploy App

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Az CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy app
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az stack group create \
            --action-on-unmanage deleteAll \
            --name my-site \
            --resource-group my-site-rg \
            --template-file iac/main.bicep \
            --deny-settings-mode 'none' \
            --parameters \
                repositoryToken=${{ secrets.STATIC_SITE_GITHUB_PAT }}
